DROP TABLE IF EXISTS BlogPost;
CREATE TABLE BlogPost (
  Id INT NOT NULL AUTO_INCREMENT,
  Content LONGTEXT CHARSET utf8mb4,
  Title LONGTEXT CHARSET utf8mb4,
  PRIMARY KEY (Id)
);
INSERT INTO BlogPost (Content,Title) VALUES ("lasagne2","rezept");