// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(SUSTestContext))]
    [Migration("20220925143341_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("UIAutomate.Models.SUSTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Agree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disagree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Neutral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StronglyAgree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StronglyDisagree")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SUSTest");
                });
#pragma warning restore 612, 618
        }
    }
}
