name: Continuous Deployment

on:
  push:
    branches: [ "UITestAutomation" ]
  workflow_dispatch:
  
jobs:
  CD:
    runs-on: self-hosted
    steps:
      - name: kill, pull and run
        run: ./runUITest.sh
